#!/bin/bash

# monitor Config
# bspc monitor eDP-1 -d 1 2 3 4 5
# bspc monitor HDMI-1 -d 5 7 8 9 0

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

#bspwm Config
bspc config border_width        3
bspc config window_gap          15
bspc config top_padding         0
bspc config right_padding       0
bspc config left_padding        0
bspc config bottom_padding      0

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer-action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer true

bspc config normal_border_color '#2D353B'
bspc config active_border_color '#A7C080'
bspc config focused_border_color '#A7C080'

# center windows
windowwidth=1280
windowheight=720

screenwidth=$(xdpyinfo | awk '/dimensions/ {print $2}' | awk -F 'x' '{print $1}')
screenheight=$(xdpyinfo | awk '/dimensions/ {print $2}' | awk -F 'x' '{print $2}')
windowx=$(echo "($screenwidth / 2) - ($windowheight / 2)" | bc)
windowy=$(echo "($screenheight / 2) - ($windowheight) / 2" | bc)

bspc rule -a float state=floating layer=above sticky=on rectangle=“$windowwidth”x”$windowheight”+”$windowx”+”$windowy”
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
